### ISSUE TITLE
TypographyTribute

### ISSUE THREAD

**Issue by juh2** [ousia/from-pandoc-to-context#1]
I had no problems to setup the ConTeXt-Suite and to compile the documentation. But I don't get the image on the title page but a huge "F", though the font TypographyTribute is installed and accessible in FontManager and LibreOffice. 

I see the font declaration in the environment, but I have no idea how it is called to make the frontpage. Where do you define the title image and what am I doing wrong?

**Comment by ousia** [comment]
@juh2, here you have the lines invoking the font:

``` tex
\def\CoverImageFile{}%\externalfigure[TypeWriter][width=\textwidth]}
\definefontfamily[ornamenta][rm][TypographyTribute]
\def\CoverImageFont{\scale[width=\textwidth]{\ornamenta F}}
\def\CoverImage{\doifsomethingelse{\CoverImageFile}{\CoverImageFile}{\CoverImageFont}}
```

The last line defines the cover image. It may be a cover image file. When there is no cover image file (such as in the first line), the cover image font is selected.

The second line defines the font. And the third line selects the "F" character.

I guess that you might have run ConTeXt for the first time before installing the font. All you have to do is to rebuild the font cache with:

```
mtxrun --script fonts --reload
```

BTW, this works with Windows and MacOS X.

In Linux, you also need to add the path to system fonts with the following line at the end of `tex/setuptex`:

```
export OSFONTDIR="/usr/share/fonts//"
```

Double slash is required to find font files in subdirectories. More values are separated with semicolons.

Let me know whether this works fine for you.

**Comment by juh2** [comment]
I rebuilt the font cache, exported OSFONTDIR and sourced setuptex again, but I still don't get the right sign but the big F.

**Comment by ousia** [comment]
Which OS do you use? Which is the path for system fonts?

Do you have another ConTeXt version (from TeX Live)? In that case, you need to rebuild the font cache with the previous sourced setuptex. Otherwise, the font cache from TeX Live would be rebuilt.

What is the output from the following commands?

```
source /path/to/context-suite &&  mtxrun --script font --list typography
```

**Comment by juh2** [comment]
```
$ source context/tex/setuptex && mtxrun -- script font --list typography
Setting "/home/juh/context/tex" as ConTeXt root.

resolvers       | trees | analyzing 'home:texmf'
resolvers       | trees | analyzing 'home:texmf'
resolvers       | trees | analyzing 'home:texmf'
```

After that I compile the docs but still I get the "F"

Linux sokrates 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

TypographyTribute is in /home/juh/.fonts/Library/T

**Comment by juh2** [comment]
I now added:

```
export OSFONTDIR="/usr/share/fonts//;$HOME/.fonts//"
```

to setuptex, resourced and rebuild the font cache but still the same "F"

**Comment by ousia** [comment]
I must confess that I don’t know what is preventing Ubuntu from recognizing the font.

First, what is the output from:

```
fc-list TypographyTribute
```

It seems that Ubuntu adds the paths in a different way (according to http://wiki.contextgarden.net/Ubuntu#Adding_the_system_fonts). The relevant part would be replacing semicolons with colons and `$HOME` with `~`.

Another thing would be to add the directory `~/.fonts/Library/`.

And another possibility that comes to my mind is removing the cache directory (`mv -i context/tex//tex/texmf-cache/luatex-cache/ ~/Desktop/` to remove it from there manually).

After that recompile the PDF document as in:

```
pandoc -S -s --section-divs -o from-pandoc-to-context.xml -t html from-pandoc-to-context.md
contextjit --purgeall --environment=from-pandoc-to-context.tex from-pandoc-to-context.xml
```

I hope one of the options works.

**Comment by ousia** [comment]
@juh2, I forgot to add when removing the cache. If you get an error when running ConTeXt after the cache removal such as:

```
mtxrun          | unknown script 'context.lua' or 'mtx-context.lua'
```

run

```
mtxrunjit --generate
```

and recompile the PDF document again.

**Comment by juh2** [comment]
```
fc-list TypographyTribute
/home/juh/.fonts/Library/T/TypographyTribute.ttf: TypographyTribute:style=Regular
/home/juh/.local/share/fonts/TypographyTribute.ttf: TypographyTribute:style=Regular
```

I tweaked it as you described, removed the cache dir etc., but no change.

**Comment by ousia** [comment]
This is really weird.

Why you have the font installed twice?

Could you remove one (or at least) move the one from `/home/juh/.fonts/Library/T/TypographyTribute.ttf` to `/home/juh/.fonts/TypographyTribute.ttf`?

You would need to delete the cache directory again.

If this doesn’t work, please provide the output from:

```
mtxrunjit --script fonts --list --all
```

**Comment by ousia** [comment]
Another way of making it work would be to create a soft link to `context/tex/texmf-fonts`, such as in:

```
ln -s /home/juh/.fonts/Library/T/TypographyTribute.ttf context/tex/texmf-fonts/
```

This has to be the last resource. Because ConTeXt should read system fonts. And in fact, it reads them (I have TypographyTribute installed on Fedora 22, not directly in ConTeXt).

**Comment by juh2** [comment]
I remove the font with font manager so that ./fonts gets empty. With the font in .local/share/fonts it works as expected. 

I don't know why but I have some fonts in .fonts and some in .local/share/fonts

**Comment by juh2** [comment]
To fix this issue I installed TypographyTribute in ./local/share/fonts.

I added this to setuptex:

```
export OSFONTDIR=~/.local/share/fonts/:/usr/share/fonts/:usr/share/texmf/fonts/opentype
```

I deleted the cache directory and ran 

```
mtxrunjit --generate
```

After that the new fonts was displayed on the titlepage.

**Comment by ousia** [comment]
> ```
> export OSFONTDIR=~/.local/share/fonts/:/usr/share/fonts/:usr/share/texmf/fonts/opentype
> ```

@juh2, I would add a back slash before the last path. Is this path relative or absolute?
