### ISSUE TITLE
include-after is included after dedication, epigraph etc. in EPUB

### ISSUE THREAD

**Issue by juh2** [ousia/from-pandoc-to-context#15]
When I create an EPUB the contents of --variable include-after="foo" is not only included at the end of the book but also after makeups such as epigraph, copyright and dedication.

**Comment by ousia** [comment]
Not sure this bug belongs here. I have nothing to do with ePub generation.

Or am I missing something?

**Comment by juh2** [comment]
Its an epub template issue. Sorry for the noise.
