### ISSUE TITLE
Footnote problem

### ISSUE THREAD

**Issue by juh2** [ousia/from-pandoc-to-context#18]
This is a strange issue for which I am unable to produce a mwe. 

Some of my footnotes in my last book does not appear on the page where the footnote sign is set. Did you ever encountered such a problem?

The footnotetext is set on the following page. I never had this problem with LaTeX so I have no idea how to fix this.

**Comment by ousia** [comment]
Yes, it happened to me.

I solved it using the following options in `\setupfootnote`:

``` tex
     split=verystrict,
     scope=text,
```

If this doesn’t fix it (they are included in `from-pandoc-to-context.tex`, the styling file), you should report it at the mailing list.

**Comment by juh2** [comment]
Thanks for the fast reply.

I had this completely commented out for some reason:

```
\setupnote
    [footnote]
    [way=bytext,
%     location=page,
     split=verystrict,
     scope=text,
%     align=strict,
     rule=on,
     bodyfont=8pt,
%     numberstyle=\tf,
%     before={\vskip0pt},
%     textcommand={\hairspace\high},
%     before=\directsetup{setups:footnotes}
     ]
```

I am not sure which options I need. With this it looks good.

**Comment by ousia** [comment]
I think the problem was solved. I’m closing the issue.

Let me know if I have to reopen it again.
