### ISSUE TITLE
centered paragraphs

### ISSUE THREAD

**Issue by juh2** [ousia/from-pandoc-to-context#19]
I don't know how to get centered paragraphs with pandoc and context. Any hints?

**Comment by ousia** [comment]
The solution would be better if attributes were enabled in Markdown for paragraphs. But anyway, your source code may read

``` xml
<div class="centered">
Your centered paragraph comes here.

One or many ones
</div>
```

You should add to your CSS file (file specified in `stylesheet` in YAML metadata):

``` css
div#centered {
    text-align: center;
}
```

And you should add to your `pandoc-xhtml.tex` source (I want to update mine, but I messed my local git repo :cold_sweat:):

``` tex
\xmlsetsetup{\xmldocument}
    {div[@class='centered']}
    {xml:centeredblock}

\startxmlsetups xml:centeredblock
    \startalign[center]\xmlflush{#1}\stopalign
\stopxmlsetups
```

**Comment by juh2** [comment]
Thanks a lot.

In my case the CSS has to be

```
div.centered p {
    text-align: center;
}
```

I hope you can save your repo.

**Comment by ousia** [comment]
@juh2, you’re right, it was a newbie mistake.

My selector was for a unique identifier and the code requires a class.

Although this should work too:

``` css
div.centered {
    text-align: center;
}
```

That centers the whole block (the division), no matter which elements it contains.

[As not done previously, I have tested the above CSS code myself.]
