### ISSUE TITLE
footnotes not being displayed

### ISSUE THREAD

**Issue by ousia** [ousia/from-pandoc-to-context#2]
I have to check it later.

``` markdown
Text^[footnote]
```

Footnote references in text are displayed, but footnotes themselves aren’t.

**Comment by ousia** [comment]
@juh2, there is nothing wrong in `pandoc-xhtml` (the main environment).

The book environment (`from-pandoc-to-context.tex`) specifies footnotes as endontes. If you want footnotes, you will have to replace:

``` tex
\setupnote
    [footnote]
    [way=bytext,
     location=text,
     split=verystrict,
     scope=text,
     align=strict,
     rule=off,
     numberstyle=\tf,
     bodyfont=,
     before=\vskip0pt,
     textcommand={\hairspace\high},
     before=\directsetup{setups:footnotes}]
```

with

``` tex
\setupnote
    [footnote]
    [way=bytext,
     split=verystrict,
     scope=text,
     align=strict,
     rule=off,
     numberstyle=\tf,
     bodyfont=,
     before=\vskip0pt,
     textcommand={\hairspace\high},
     before=\directsetup{setups:footnotes}]
```

This is actually removing `location=text` from `\setupnote[footnote]`.

Although I should arrange the main environment, otherwise there would be an empty chapter titled _Notes_ (or _Notizen_, when the mainlanguage is German).

**Comment by juh2** [comment]
Changing that displays the footnotes at the bottom of the page.

But how do I invoke endnotes in the text? I am using the eonvironment with a text of mine which is not structured in the same way as the documentation, but I cannot find a command there that says insert here the references.

**Comment by ousia** [comment]
Short answer: I’m afraid you can’t.

I haven’t implemented this, because this should be implemented in `pandoc` itself (see jgm/pandoc#1720).

`pandoc` should give the user the ability to locate table of contents, footnotes and references, where (s)he wants in the document. I think these are reasonable features.

**Comment by ousia** [comment]
@juh2, probably we could find a compromise fix until `pandoc` implements the feature to locate footnotes.

What do you need? I think we could have a `<juh:footnotes />` tag which could invoke a chapter with a title (no numbering) and the footnotes (as displayed in `from-pandoc-to-context.pdf').

Is it OK? What would you change for your element?

**Comment by juh2** [comment]
I am afraid that I don't understand your proposal / question. 

I don't understand how you managed invocation of footnotes in from-pandoc-to-context.pdf as they appear there and not in my text, where I use the same environments as you in your file.

**Comment by ousia** [comment]
Sorry, commit 58201482a70fc593faee78c64e6f926bcf269b90 should fix it.

You have now a `<juh:footnotes />` element. Place it wherever you want in your document. It should place all your endnotes there.

You should add `--mode=juh:footnotes` when invoking ConTeXt to avoid an empty chapter with a _Notes_ / _Notizen_ title (invoked by default by `pandoc-xhtml.tex`, not in `from-pandoc-to-context.tex`).

Let me know if everything is clear now. And if the implementation suits your needs.

**Comment by juh2** [comment]
Sorry, but I am lost. 

I updated pandoc-xhtml.tex and put <jul:footnotes /> somewhere in the text. (You used jul instead of juh)

Then I invoked context with environment from-pandoc-to-context and --mode=jul:footnotes but no footnotes show up. 

Still I don't understand how YOU invoked footnotes in from-pandoc-to-context.pdf. 

BTW: I ordered the Layout in ConTeXt book. ;-)

**Comment by ousia** [comment]
Sorry for not being clear (and for the typo [corrected in cd6248a200e40fd8797c67dad6c3bffccf6f2b80]).

Let’s try the following (let’s call it `sample.md`):

``` markdown
# Chapter

a^[note]

# Chapter

a^[note]

# Chapter

a^[note]

# Chapter

a^[note]

# Chapter

a^[note]

# Chapter

a^[note]

# Chapter

a^[note]

<juh:footnotes />
```

And then compile with `--mode=juh:footnotes,endnotes` (no space after the comma). I guess the missing second mode was the reason it didn’t work.

At least, it works with `sample.md` (just tested).

BTW, footnotes in `from-pandoc-to-context.md` are automatically added before the chapter with the any of the `.colophon` or `#colophon` attributes. This is specified in `pandoc-xhtml.tex`.

**Comment by juh2** [comment]
Ok. Now it works with sample.md perfectly. But in my real text I don't get the chapter title "Notes" or "Notizen" only the notes. 

BTW: "Anmerkungen" would be better than "Notizen".

**Comment by ousia** [comment]
> BTW: "Anmerkungen" would be better than "Notizen".

Just fixed.

> Ok. Now it works with sample.md perfectly. But in my real text I don't get the chapter title "Notes" or "Notizen" only the notes. 

Sorry, my fault.

I was wrong with language modes. Buggy implementation could be only triggered `de-DE` or `en-UK`. `es-ES` worked fine (although I only use `es`).

Fixed in commit 6966ad7db0d110f6eaeb714b8867a10ec47a8adc.

**Comment by ousia** [comment]
@juh2, sorry, but I forgot this comment.

As you may already know, this only affects to the PDF document generated by ConTeXt.

ePub documents will have its footnotes at the end of each chapter.

**Comment by juh2** [comment]
Great. It works.
