### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by AidanNichol** [ousia/from-pandoc-to-context#21]
I'm doing some experiments with this and everything is going fine but I'm sure that one day I'm going to hit a problem. The approach of mapping xhtml to context which will generate my pdf gives a lot of flexibility but is a non-trivial process that might be easy to get wrong. is there any way to capture the resulting context stream so I can see if I made errors in the mapping from `XML`

**Comment by ousia** [comment]
I’m not aware of that possibility. I don’t even think that there is something such as a translation to ConTeXt source in the XML handling.

But if this isn’t related to this particular environment (`pandoc-xhtml.tex`), the [mailing list](https://mailman.ntg.nl/mailman/listinfo/ntg-context) is the best place to ask for these questions.

Sorry, but I’m not a ConTeXt expert myself.

**Comment by ousia** [comment]
It may be worth to ask for this feature in the mailing list. This issue is closed.
