### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by trenkert** [ousia/from-pandoc-to-context#22]
Could you give a minimal example on how to use pandoc2context? I only saw the 60+ pages long documentation but don't have the time to read through it before knowing if it can be useful to me. Could you provide a small example and a short tutorial on how to use it?

**Comment by ousia** [comment]
@trenkert, the sample is already there:

1. `git clone https://github.com/ousia/from-pandoc-to-context.git`

1. `cd from-pandoc-to-context/doc`

1. `pandoc -S -s --section-divs -o from-pandoc-to-context.xml -t html from-pandoc-to-context.md`

1. `contextjit --purgeall --environment=from-pandoc-to-context.tex from-pandoc-to-context.xml`

1. Once you compile a PDF document (where some goodies might be missing), start modifying both Markdown and ConTeXt files.

Sorry for the next statements, if they are too assertive. I don’t really have (almost any) time for this project.

If you don’t have time to page through the documentation, you won’t have time to learn how to use the method proposed here.

If you have no previous ConTeXt experience, you will have to find some time to learn how to use it.

I hope it helps.

**Comment by ousia** [comment]
@trenkert, sorry you don’t seem to care anymore, so I’m closing the issue.
