### ISSUE TITLE
Coverpage hardcoded

### ISSUE THREAD

**Issue by juh2** [ousia/from-pandoc-to-context#5]
The Coverpage with the image from the TypographyTribute font is hardcoded. 

I my production process with Createspace I don't need a coverpage in the book block. The cover is uploaded separately with frontcover, spine and backcover. So I would switch it off by deleting all code lines in the environments. 

Perhaps you can make it optional like other special pages like Colophon and Dedication.

**Comment by ousia** [comment]
I have just added (f0b9a0856dd90077f2d8215eca27cb19db0dc72a) a `no-coverpage` mode.

Making it optional doesn’t make sense to me, since all data in the cover page (such as in the title page) come from metadata.

**Comment by ousia** [comment]
Closing the issue myself, @juh2.

Of course, reopen it when you need it.

**Comment by juh2** [comment]
I don't know why but today I get 2 pages before the titlepage as if I have an empty coverpage. Did you change anything yesterday with the implementation of no-coverpage?

**Comment by ousia** [comment]
Not that I am aware of. 

The commit (f0b9a0856dd90077f2d8215eca27cb19db0dc72a) is really simple. I wrapped the code inside a not mode, that is something that will be ignored if the mode is invoked.

Are those two pages compietely blank or do they have any content? If they have content, which one?

I have checked this feature yesterday and today and it works fine with _From `pandoc` to ConTeXt_ and with another document.

Does `--mode=no-coverpage` add the two pages before the title page when compiling `from-pandoc-to-context.tex`?

**Comment by juh2** [comment]
When I compile my project with the original `from-pandoc-to-context.tex` I have no empty coverpage. So I must have confused my layout environment. 

I had a look with diff but saw nothing that would explain the difference.

I'll send you the layout environment by mail, because Github does not accept the filetype .tex
