### ISSUE TITLE
Style of footnotes

### ISSUE THREAD

**Issue by juh2** [ousia/from-pandoc-to-context#7]
I am trying to style the footnotes. 

```
\setupnote
[footnote]
[way=bytext,
 location=page,
 split=verystrict,
 scope=text,
 align=strict,
 rule=on,
 numberstyle=\tf,
 bodyfont=5pt,
 before=\vskip0pt,
 distance=1ex,
 textcommand={\hairspace\high},
 before=\directsetup{setups:footnotes}]
```

The bodyfont only applies to the first footnote. All following footnotes are at textsize.

before and distance seems to have no effect.

**Comment by ousia** [comment]
This is the wrong option. It sets up the font in the body, not in the note.

```
\setupnotation
    [footnote]
    [numbercommand=\tfxy,
     numberconversion=numerals,
     alternative=serried,
     style=\tfxy]
```

The `style` option from `\setupnotation` is what you need.

Notes have two setup commands. This is an exception rather than the rule in ConTeXt.

**Comment by ousia** [comment]
BTW, I wonder whether five points is readable.

**Comment by juh2** [comment]
I tried both but I get no change. It feels as if there is something missing. 

What do you mean with "font in the body"?

**Comment by ousia** [comment]
Sorry, the command was wrong:

``` tex
\setupnotation
    [footnote]
    [numbercommand={\switchtobodyfont[5pt]},
     numberconversion=numerals,
     alternative=serried,
     style={\switchtobodyfont[5pt]}]
```

With “font in the body”, I meant the footnote reference number in the main text.

I hope it works and is clearer now.

**Comment by ousia** [comment]
@juh2, did the previous comment solve the problem?

**Comment by ousia** [comment]
@juh2, I assume the problem is fixed.
