### ISSUE TITLE
blockquote styling

### ISSUE THREAD

**Issue by juh2** [ousia/from-pandoc-to-context#8]
Blockquote are mapped like this:

```
\startxmlsetups xml:blockquote 
     \blank\startnarrow\xmlflush{#1}\stopnarrow\blank
\stopxmlsetups
```

I don't see how to style this in the styling environment. 

AFAICS there is no ConTeXt equivalent to \begin{quote}\end{quote} in LaTeX. So what can be done?

**Comment by ousia** [comment]
http://wiki.contextgarden.net/Command/setupnarrower is the ConTeXt equivalent.

What do you need for block quotes?

**Comment by juh2** [comment]
As there is a vertical space before and after the quote I'd remove identation of the first line in the first paragraph.

**Comment by ousia** [comment]
Just added the element (commit 7bdb51c04b881e1b377747e61411d856bdbebd7c) :

You may want to set it up with the following code:

``` tex
\setupstartstop
    [blockquote]
    [before={\startnarrow\setupindenting[yes,next]},
     after={\stopnarrow}]
```

**Comment by ousia** [comment]
I close this issue, @juh2.

Reopen if you have problems  handling the `<blockquote>` element in ConTeXt.
